---
# tasks file for rabbitmq-packages

- include: redhat.yml
  when: ansible_os_family == 'RedHat'

- include: debian.yml
  when: ansible_os_family == 'Debian'
  
- name: Configure RabbitMQ.
  include: rabbitmq.yml
